name: oauth_chopper
description: Add and manage OAuth2 authentication for your Chopper client.
version: 0.1.0
homepage: https://github.com/DutchCodingCompany/oauth_chopper

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  chopper: ^7.0.4
  oauth2: ^2.0.2

dev_dependencies:
  http: ^1.1.0
  lints: ^2.1.1
  mocktail: ^1.0.0
  test: ^1.24.6
