name: oauth_chopper
description: Add and manage OAuth2 authentication for your Chopper client.
version: 0.0.2
homepage: https://github.com/DutchCodingCompany/oauth_chopper

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  chopper: ^5.0.0
  oauth2: ^2.0.0

dev_dependencies:
  build_runner: ^2.2.1
  lints: ^2.0.0
  test: ^1.21.6
  mockito: ^5.3.0
  http: ^0.13.5
