name: oauth_chopper
description: Add and manage OAuth2 authentication for your Chopper client.
version: 1.1.1
homepage: https://github.com/DutchCodingCompany/oauth_chopper

environment:
  sdk: ^3.6.1
  flutter: ">=3.27.0"

dependencies:
  chopper: ^8.0.4
  http: ^1.3.0
  http_parser: ^4.1.2
  oauth2: ^2.0.3

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.14
  very_good_analysis: ^7.0.0
