name: oauth_chopper
description: Add and manage OAuth2 authentication for your Chopper client.
version: 1.1.0
homepage: https://github.com/DutchCodingCompany/oauth_chopper

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  chopper: ^8.0.1+1
  http: ^1.2.2
  http_parser: ^4.1.0
  oauth2: ^2.0.3

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0
