name: oauth_chopper
description: Add and manage OAuth2 authentication for your Chopper client.
version: 0.3.0
homepage: https://github.com/DutchCodingCompany/oauth_chopper

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  chopper: ^7.2.0
  http: ^1.2.1
  oauth2: ^2.0.2

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
